spring:
 application:
  name: thinkpro-transaction

# Database  
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://thinkpro.clyvt3cy0z8c.us-east-1.rds.amazonaws.com:3306/thinkprobankdb
  username: thinkpro
  password: thinkpro
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  
server:
 port: 9093

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka
   preferIpAddress: true








